[project]
name = "bookstore-app"
version = "0.1.0"
description = "Bookstore API"
authors = [
    {name = "Evaldoer",email = "evaldorode@gmail.com"}
]
readme = "README.md"
<<<<<<< Updated upstream
requires-python = ">=3.13"
dependencies = [
    "django (>=5.2.8,<6.0.0)",
    "djangorestframework (>=3.16.1,<4.0.0)"
]

[dependency-groups]
dev = [
    "pytest (>=9.0.1,<10.0.0)",
    "factory-boy (>=3.3.3,<4.0.0)"
]

=======
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.1.3"
djangorestframework = "^3.15.2"
django-extensions = "^3.2.3"
django-debug-toolbar = "^4.4.6"
psycopg2-binary = "^2.9.11"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
pytest-django = "^4.9.0"
factory-boy = "^3.3.1"
black = "^24.10.0"
isort = "^5.13.2"
flake8 = "^7.1.1"

[tool.poetry.scripts]
manage = "django.core.management:execute_from_command_line"
>>>>>>> Stashed changes

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
